pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url = uri("https://cache-redirector.jetbrains.com/intellij-plugin-maven-releases")
        }
        maven {
            url = uri("https://cache-redirector.jetbrains.com/intellij-dependencies")
        }
        maven {
            url = uri("https://cache-redirector.jetbrains.com/intellij-repository/releases")
        }
    }
}

plugins {
    id 'org.jetbrains.intellij.platform' version '2.18.1' apply false
}

rootProject.name = 'private-reader'
